### ISSUE TITLE
  Import from MoneyMoney “unchecked”

### ISSUE THREAD

**Issue by zigulle** [NikxDa/actual-moneymoney#14]
Hello,
Whenever I make an import from MoneyMoney to Actual, the transactions are marked as “checked”. Even if they are not marked as “checked” in MoneyMoney. 
For traceability it would be easier if the “checked” field is not set during the import.

**Comment by NikxDa** [comment]
@zigulle Please excuse my delay in getting back to you on this. I can't reproduce this on my end – while there are some import issues with checked/unchecked transactions when they update between states at the moment, unchecked transactions should still come through fine.

Can you let me know what version of MoneyMoney / Actual / Actual-Moneymoney you are using, please?

**Comment by zigulle** [comment]
Hello,

I believe I did not present the feature request correctly. All transactions are transferred and synced in Actual. However, the "checked" status is not transferred.

What I mean is that it would be nice if a transaction that is marked as "checked" in MoneyMoney (checkmark behind the transaction) is also recorded as "checked" or "cleared" in Actual. Conversely, of course, if a transaction in MoneyMoney has not yet been marked as "checked," it should not be recorded as "cleared" in Actual.

Currently, all transactions in Actual are recorded as "cleared," regardless of the "checked" status in MoneyMoney.

My MoneyMoney version is 2.4.42, Actual 2.4.11, and actual-moneymoney 2.5.0.

I hope the feature request is clearer now.

**Comment by NikxDa** [comment]
Hey @zigulle,

thanks for providing more information. I feel like I need to understand more about the way you are using MoneyMoney to make sense of this.

First, let's clear up the terminology so we're talking about the same things:

- In Actual, there is a checkmark all the way on the right hand side, used to mark `cleared` transactions. Cleared in this instance means that the money was actually deducted from the account, and the transaction is not pending.
- In MoneyMoney, there are two boolean statuses, `booked` and `checked`. Pending transactions show up with a striped background, and have `booked` set to false. Additionally, there is a status for checkboxes on the right hand side, called `checked`.

Currently, the import logic maps MoneyMoney's `booked` state to Actual's `cleared` state. As far as I can tell, this is correct. Do I understand that you want to map the checkboxes on the right hand side instead? Why? Can you describe your use case?

I could make this an optional setting if it provides any value.

Cheers

**Comment by NikxDa** [comment]
@zigulle Closing this for now as I haven't heard back. If you elaborate your use case, I can reopen :)

**Comment by NikxDa** [comment]
@zigulle Thanks for providing more detailed feedback. I'm not quite sure I fully understand how you're using the cleared status when considering Actual's reconciliation feature, but by the sounds of it, giving you an option to not synchronize the cleared status from MoneyMoney to Actual should solve your issue?

I've just released version 2.6.0 with a new configuration option called `synchronizeClearedStatus`. This is a boolean value that can be set under the `[import]` key in the configuration file.

It defaults to `true`, but if you set it to `false`, the importer will no longer import the booked field  from MoneyMoney's cleared state.

Please let me know if this solves your problem.

Cheers
Nik

**Comment by zigulle** [comment]
Hallo Nik,

thanx a lot!!! This solves my problem.

Cheers
Daniel
