### ISSUE TITLE
Feature Request: Consider an option to ignore transactions which are not yet booked

### ISSUE THREAD

**Issue by MirkoDziadzka** [NikxDa/actual-moneymoney#6]
Please consider the following feature request:

- As a user, I do not want to import transactions which are not already marked as "booked" into MoneyMoney

Background:

Depending on the account type and bank, some transactions are marked as "not yet booked" in MoneyMoney. These transactions may get deleted by the bank or may change its value before they are finally booked. See the first transaction in the screenshot below.

I do not want to import them into the budget yet.

![Screenshot 2024-01-19 at 15 55 01](https://github.com/NikxDa/actual-moneymoney/assets/1268043/2227f129-1809-4711-acee-d8c695b795ca)

Some users may want to have them, so I propose to make this a config option.

**Comment by NikxDa** [comment]
This has been added in the latest version as `importUncheckedTransactions` in the config file.
Note that the newest version should also mark transactions as booked on the next import if the booking state has changed in MoneyMoney.
